2021-10-22 19:50:08,498 -- ============ Training routine: "configs/LMSCNet_SS.yaml" ============

2021-10-22 19:50:08,846 -- => Loading network architecture...
2021-10-22 19:50:09,007 -- => Loading optimizer...
2021-10-22 19:50:09,008 -- => Loading scheduler...
Traceback (most recent call last):
  File "train.py", line 345, in <module>
    main()
  File "train.py", line 338, in main
    model1,optimizer,scheduler,epoch = checkpoint.load_LMSC(model1,optimizer,scheduler,_cfg._dict['STATUS']['RESUME'],_cfg._dict['STATUS']['LAST'],logger)
  File "/home/eegroup/eefrank/b07901031/SSCNet/Try_Try/common/checkpoint.py", line 21, in load_LMSC
    file_path = sorted(glob(os.path.join(path, '*.pth')))[0]
IndexError: list index out of range
